import 'dart:typed_data';

import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

class PdfService {
  Future<Uint8List> generatePdf({
    required List<pw.Widget> content,
    String? title,
    PdfPageFormat pageFormat = PdfPageFormat.a4,
    bool landscape = false,
  }) async {
    final pdf = pw.Document(
      title: title ?? 'SurgiTrack Report',
      author: 'SurgiTrack',
    );

    final format = landscape ? pageFormat.landscape : pageFormat;

    pdf.addPage(
      pw.MultiPage(
        pageFormat: format,
        margin: const pw.EdgeInsets.all(28),
        header: (context) => _buildHeader(title),
        footer: (context) => _buildFooter(context),
        build: (context) => content,
      ),
    );

    return pdf.save();
  }

  pw.Widget _buildHeader(String? title) {
    return pw.Container(
      margin: const pw.EdgeInsets.only(bottom: 12),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Text(
            'SurgiTrack',
            style: pw.TextStyle(fontSize: 11, fontWeight: pw.FontWeight.bold),
          ),
          if (title != null)
            pw.Text(title, style: const pw.TextStyle(fontSize: 9)),
        ],
      ),
    );
  }

  pw.Widget _buildFooter(pw.Context context) {
    return pw.Container(
      margin: const pw.EdgeInsets.only(top: 12),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Text(
            'Generated by SurgiTrack',
            style: const pw.TextStyle(fontSize: 8),
          ),
          pw.Text(
            'Page ${context.pageNumber} of ${context.pagesCount}',
            style: const pw.TextStyle(fontSize: 8),
          ),
        ],
      ),
    );
  }

  Future<void> previewPdf({required Uint8List pdfBytes}) async {
    await Printing.layoutPdf(
      onLayout: (PdfPageFormat format) async => pdfBytes,
    );
  }
}
