import 'package:pdf/widgets.dart' as pw;

import 'package:surgitrack/features/reports/domain/portfolio_snapshot_data.dart';

class PortfolioSnapshotPdfGenerator {
  List<pw.Widget> build(PortfolioSnapshotData data) {
    return [
      pw.Text(
        "SurgiTrack",
        style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold),
      ),

      pw.SizedBox(height: 8),

      pw.Text("Training Portfolio Snapshot", style: pw.TextStyle(fontSize: 18)),

      pw.SizedBox(height: 20),

      _section("Portfolio Overview", [
        ["Total Cases", data.totalCases],

        ["Total Patients", data.totalPatients],

        ["Total Procedures", data.totalProcedures],
      ]),

      _section("Specialty Exposure", [
        ["Cardiac Cases", data.cardiacCases],

        ["Thoracic Cases", data.thoracicCases],

        ["Vascular Cases", data.vascularCases],
      ]),

      _section("Operative Role Exposure", [
        ["Performed Independently", data.independentCases],

        ["Performed Under Supervision", data.supervisedCases],

        ["Assisted", data.assistedCases],

        ["Observed", data.observedCases],
      ]),

      pw.SizedBox(height: 30),

      pw.Divider(),

      pw.Text(
        "Generated by SurgiTrack",
        style: const pw.TextStyle(fontSize: 10),
      ),
    ];
  }

  pw.Widget _section(String title, List<List<dynamic>> rows) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,

      children: [
        pw.SizedBox(height: 15),

        pw.Text(
          title,
          style: pw.TextStyle(fontSize: 15, fontWeight: pw.FontWeight.bold),
        ),

        pw.SizedBox(height: 8),

        pw.TableHelper.fromTextArray(
          headers: ["Metric", "Count"],

          data: rows.map((e) => [e[0], e[1].toString()]).toList(),
        ),
      ],
    );
  }
}
