import 'package:flutter/material.dart';

class ReportFooter extends StatelessWidget {
  const ReportFooter({super.key});

  @override
  Widget build(BuildContext context) {
    return const Padding(
      padding: EdgeInsets.only(top: 20),

      child: Text("Generated by SurgiTrack", style: TextStyle(fontSize: 12)),
    );
  }
}
